version: "3.9"  # optional since v1.27.0
services:
  api:
    build: api
    command: python server.py
    volumes:
      - ./api:/usr/app/
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
  requests:
    build: requests
    command: node index.js
    volumes:
      - ./requests:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    links: 
      - api