version: "3.9"  # optional since v1.27.0
services:
  api-flask:
    build: api
    command: python server.py
    volumes:
      - ./api:/usr/app/
    ports:
      - "5000:5000"
    expose:
      - 5000 
    stdin_open: true
    tty: true
    environment:
      - DEBUG=1
      - PORT=5000

  api-express:
    build: api-express
    command: node index.js
    volumes:
      - ./api-express:/usr/app
      - /usr/app/node_modules
    ports:
      - "4000:4000"
    expose:
      - 4000 
    stdin_open: true
    tty: true
    environment:
      - DEBUG=1
      - PORT=4000

  requests:
    build: requests
    command: node index.js
    volumes:
      - ./requests:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    expose:
      - 3000
    stdin_open: true
    tty: true
    depends_on:
      - api-express
      - api-flask
    environment:
      - DEBUG=1
      - PORT=3000